import { withSeededRandom } from '@/harness/prng'

import { createGameState } from '@/engine/state'

const SEED = 42

/**
 * Explicit field list for GameState.
 * If a field is added or removed from GameState, this test fails —
 * forcing the developer to acknowledge the schema change.
 */
const EXPECTED_FIELDS = [
  'stewardName',
  'map',
  'mapWidth',
  'mapHeight',
  'player',
  'backpack',
  'playerFacing',
  'facingEntityPos',
  'camera',
  'viewportWidth',
  'viewportHeight',
  'activeDialog',
  'discoveredRecipes',
  'previewFn',
  'weather',
  'path',
  'pathWaypoints',
  'pathIsChained',
  'pendingAction',
  'cursorTile',
  'cursorScreenPos',
  'rainSeed',
  'metric',
  'currentZone',
  'overworldMap',
  'overworldMapWidth',
  'overworldMapHeight',
  'caveMap',
  'caveMapWidth',
  'caveMapHeight',
  'caveEntranceOverworld',
  'caveEntranceInterior',
  'caveRevealed',
  'caveHiddenPositions',
  'caveNpcSpot',
  'caveBreakableWallPositions',
  'houseMap',
  'houseMapWidth',
  'houseMapHeight',
  'houseEntranceOverworld',
  'houseEntranceInterior',
  'houseBedInterior',
  'houseChairInterior',
  'emilyInvitation',
  'emilyReveryReturn',
  'tenureOpened',
  'meteorShower',
  'lastSatelliteSpawnTime',
  'screenShakeUntil',
  'lightning',
  'floraGrowthPreviews',
  'floraLifecycle',
  'activeWaves',
  'overlayMode',
  'egregorePositions',
  'egregoreLifecycle',
  'lastEgregoreSpreadYear',
  'placedMeteorites',
  'stoneCirclePreview',
  'dragHoverTile',
  'soilHealth',
  'elevation',
  'ponds',
  'rivers',
  'tileWater',
  'burnScars',
  'craters',
  'manualDiscoveries',
  'manualState',
  'giftsReceived',
  'pendingInteractionTarget',
  'heldDirection',
  'sprinting',
  'trail',
  'playerTween',
  'audioEnabled',
  'fontScale',
  'world',
  'lastDialogTypingTick',
  'glintingCoins',
  'coinGlintPopTimes',
  'seedGenomes',
  'divinedHexagrams',
  'glintZones',
  'glintPatches',
  'glintOpacity',
  'lastGlintSpawnTime',
  'civilizationRuins',
  'mainQuestPhase',
  'ruinGenerationMode',
  'deepTime',
  'deepTimeTransition',
  'revery',
  'reveryCount',
  'lastReveryEndTime',
  'cosmologicalDrift',
  'revealedPhenotypes',
  'dormancyPressure',
  'collapsedStewardTile',
  'playerStationarySince',
  'lastSky',
  'postGiftActionsCompleted',
  'rainFrontOffset',
  'precipitationIntensity',
  'seasonalPhase',
  'currentDate',
  'lockedBurnLine',
  'burnLineIndex',
  'lastSeenSeason',
  'moabState',
  'wind',
  'pollen',
  'pollenTrailDepth',
  'waterProximity',
  'genesis',
  'bootTitleCard',
  'zoneTransition',
  'nextAngelSpawnTime',
  'angelFlashTime',
  'coyoteCargo',
  'ruinInteriors',
  'currentRuinIndex',
  'caveFogExplored',
  'caveFogDiscovered',
  'overworldFogExplored',
  'overworldFogDiscovered',
  'autoHidePanels',
  'panelOpenMoveCount',
  'multiplayerSession',
  'remotePlayers',
  'scannedSpecimens',
  'oakSpecimens',
  'egregoreSpecimens',
  'scanInProgress',
  'manualHighlightEntryId',
  'onPlayerMoved',
  'onGenesisComplete',
  'heldKeys',
  'cameraFilm',
  'placedCameras',
  'cameraArchive',
  'playbackCameraUid',
  'photographAlbum',
].sort((a, b) => a.localeCompare(b))

describe('GameState schema', () => {
  it('has exactly the expected fields', () => {
    const state = withSeededRandom(SEED, () => createGameState('test', 40, 30))
    const actualFields = Object.keys(state).sort((a, b) => a.localeCompare(b))

    expect(actualFields).toEqual(EXPECTED_FIELDS)
  })

  it('field count matches', () => {
    const state = withSeededRandom(SEED, () => createGameState('test', 40, 30))

    expect(Object.keys(state)).toHaveLength(EXPECTED_FIELDS.length)
  })
})
