name = "revery-prairie-worker"
main = "src/index.ts"
compatibility_date = "2026-04-25"

[[durable_objects.bindings]]
name = "PRAIRIE"
class_name = "PrairieDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PrairieDO"]
